"""Creates/removes the ~/.sieve/bin/claude shim and discovers the real Claude binary."""

from __future__ import annotations

import os
import shlex
import shutil
import stat
import sys
from pathlib import Path

from sieve.config import BIN_DIR, SHIM_PATH

# Absolute paths are baked in at `sieve on` time so the shim keeps working in
# shells where sieve's venv isn't activated — and if sieve itself disappears
# (venv deleted), it falls through to the real claude instead of breaking it.
SHIM_TEMPLATE = """#!/usr/bin/env bash
# Generated by Sieve (`sieve on`). Remove with `sieve off`.
SIEVE_BIN={sieve_bin}
REAL_CLAUDE={real_claude}
if [ -x "$SIEVE_BIN" ]; then
    exec "$SIEVE_BIN" run claude "$@"
fi
if [ -x "$REAL_CLAUDE" ]; then
    echo "sieve: sieve binary not found — passing through to real claude" >&2
    exec "$REAL_CLAUDE" "$@"
fi
echo "sieve shim: neither sieve nor the real claude binary is executable." >&2
echo "Fix: reinstall sieve, or delete this shim: {shim_path}" >&2
exit 127
"""


def _sieve_executable() -> str:
    """Absolute path of the running sieve entry point, for baking into the shim."""
    found = shutil.which("sieve")
    if found:
        return found
    # Fallback: the console script that invoked us (works inside a venv even
    # when the venv's bin dir isn't on PATH).
    return sys.argv[0] or "sieve"


def find_real_claude(path_env: str | None = None) -> str | None:
    """Searches PATH for a 'claude' executable, skipping Sieve's own bin dir
    so 'sieve on' never detects its own shim as the real binary."""
    path_env = path_env if path_env is not None else os.environ.get("PATH", "")
    bin_dir_resolved = BIN_DIR.resolve()

    for entry in path_env.split(os.pathsep):
        if not entry:
            continue
        entry_path = Path(entry)
        try:
            if entry_path.resolve() == bin_dir_resolved:
                continue
        except OSError:
            continue
        candidate = entry_path / "claude"
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


def write_shim(real_claude_path: str) -> Path:
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    script = SHIM_TEMPLATE.format(
        sieve_bin=shlex.quote(_sieve_executable()),
        real_claude=shlex.quote(real_claude_path),
        shim_path=SHIM_PATH,
    )
    SHIM_PATH.write_text(script)
    SHIM_PATH.chmod(SHIM_PATH.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return SHIM_PATH


def remove_shim() -> bool:
    if SHIM_PATH.exists():
        SHIM_PATH.unlink()
        return True
    return False


def shim_installed() -> bool:
    return SHIM_PATH.is_file() and os.access(SHIM_PATH, os.X_OK)


PATH_MARKER = "# sieve: add shim to PATH"


def default_shell_rc() -> Path:
    """Best-effort guess at the rc file the user's interactive shell sources."""
    shell = os.environ.get("SHELL", "")
    home = Path.home()
    if "zsh" in shell:
        return home / ".zshrc"
    if "bash" in shell:
        bash_profile = home / ".bash_profile"
        return bash_profile if bash_profile.exists() else home / ".bashrc"
    return home / ".profile"


def persist_path(rc_path: Path) -> bool:
    """Idempotently appends the shim's PATH export to rc_path.
    Returns True if a new line was written, False if already present."""
    existing = rc_path.read_text() if rc_path.exists() else ""
    if PATH_MARKER in existing:
        return False
    rc_path.parent.mkdir(parents=True, exist_ok=True)
    with rc_path.open("a") as f:
        f.write(f'\n{PATH_MARKER}\nexport PATH="$HOME/.sieve/bin:$PATH"\n')
    return True


def path_order_correct(path_env: str | None = None) -> bool:
    """True if BIN_DIR appears in PATH before any other 'claude' binary's dir."""
    path_env = path_env if path_env is not None else os.environ.get("PATH", "")
    bin_dir_resolved = BIN_DIR.resolve()
    for entry in path_env.split(os.pathsep):
        if not entry:
            continue
        entry_path = Path(entry)
        try:
            resolved = entry_path.resolve()
        except OSError:
            continue
        if resolved == bin_dir_resolved:
            return True
        if (entry_path / "claude").is_file():
            return False
    return False
